zuul: 
  prefix: /api
  routes: 
    dms-create: 
      path: /dms-create/**
      #url: https://dms-create:8072
    dms-report: 
      path: /dms-report/**
    dms-search: 
      path: /dms-search/**
      #url: https://dms-search:8074

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    hostname: localhost

server:
  port: 8079

spring:
  application:
    name: zuul-service

