spring:
  application:
    name: dms-search

server:
  port: 8074

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8070/eureka/
  instance:
    hostname: localhost